name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Testing message
        if: ${{ contains(join(github.event.commits.*.message), '#skip')}}
        run: echo 'HERE!'

      - name: Trigger deployment
        # Need to config it so that if a commit message contain #skip, it is not deployed
        if: ${{ !contains(join(github.event.commits.*.message), '#skip') && github.event_name == 'push'}}
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

      # Send Discord notification
      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@4f4322cb1878ec4400fcf6a10315d2169a90877d
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.FS_DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: 'Testing content'
          title: 'Deployment successful!'
          description: |
            **Commit**: `${{ github.sha }}`
            **Message**: `${{ join(github.event.commits.*.message) }}`
            **Author**: `${{ github.actor }}`

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      # Check out the current repo first !important
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        if: ${{ !contains(join(github.event.commits.*.message), '#skip') && github.event_name == 'push'}}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
